{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b0a37a8-ba39-46e5-94a8-b97e92780d4d",
   "metadata": {},
   "outputs": [],
   "source": [
    "using DifferentialEquations, DataFrames, Plots"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "289bd01d-1cd0-437c-a92e-dd614077635f",
   "metadata": {},
   "outputs": [],
   "source": [
    "function model!(du,u,h,p,t)\n",
    "    r_v_epi_ua, d_v_ua, e_v_ig_ua, m_v_lungs, d_ep_ua, ep_0_ua, i_v_ep_ua, a_epe_epi_ua, e_epi_ctl_ua, d_epi_ua,\n",
    "    d_idc_ua, idc_0_ua, p_idc_ua, s_v_idc_recr_ua, m_idc_ln_ua, s_v_idc_migr_ua, d_mdc_ua, p_cd8_ua, s_mdc_cd8_prol_ua,\n",
    "    a_cd8_ctl_ua, s_mdc_cd8_diff_ua, d_cd8_ua, cd8_ua, d_ctl_ua, m_ctl_ua, p_b_ua, s_mdc_b_prol_ua, d_b_ua, b_0_ua, a_b_ua,\n",
    "    s_mdc_b_diff_ua, d_p_ua, r_ig_ua, d_ig_ua, t_ctl_ua, ep_0, idc_0, m_0, p_mr, i_v_ep, p_idc, r_v, a_mr_ma, s_v_mr_act, s_v_idc_recr,\n",
    "    s_ifn_ep_inf, a_ma_mr, a_epe_epi, e_epi_ctl, e_v_igg,\n",
    "    e_v_iga, e_v_igm, d_v, d_idc, d_ep, d_epi, d_ma, d_mr, m_ctl_lungs, s_ifn_mr_act, t_ctl, b_0, cd4_0, cd8_n, s_il2_t_prol,\n",
    "    r_ifn_th1, r_il12_ma, r_il12_mdc, r_iga, r_igg, r_igm, p_b, r_ifn_ctl, a_cd8_ctl, a_cd4_th1, a_cd4_tfh, a_b_p, s_mdc_b_prol, s_v_idc_migr,\n",
    "    s_mdc_cd8_prol, s_mdc_cd4_prol, s_il6_t_prol, p_cd4, p_cd8, r_il6_epi, r_il2_tfh, r_il2_th1, r_il6_ma, d_iga, d_igg, d_igm, d_b, d_mdc,\n",
    "    d_p, d_t, d_il6, d_il12, d_th1, d_tfh, d_ifn, d_ctl, d_il2, m_idc_ln, s_tfh_b, s_il12_cd4_diff, s_il6_cd4_diff, s_v_ifn_prod, t_idc,\n",
    "    e_1, e_2, e_3, e_4, e_5, e_6, e_7, e_8, s_il6_epi_elim = p\n",
    "    \n",
    "    v_ua, ep_ua, epe_ua, epi_ua, idc_ua, mdc_ua, tn_ua, ctl_ua, ctl_act_ua, bn_ua, p_ua, ig_ua, v_l, ep_l, epe_l, epi_l, idc_l, mdc_l, hn_l, tn_l, ctl_l, th1_l, tfh_l, ctl_act_l, bn_l, p_l, igg_l, iga_l, igm_l, mr_l, ma_l, igamma_l, i2_l, i6_l, i12_l = u\n",
    "    \n",
    "    dv_ua = r_v_epi_ua * epi_ua - d_v_ua * v_ua - e_v_ig_ua * ig_ua * v_ua - m_v_lungs * v_ua\n",
    "    dep_ua = d_ep_ua * ep_0_ua - d_ep_ua * ep_ua - i_v_ep_ua * v_ua * ep_ua\n",
    "    depe_ua = i_v_ep_ua * v_ua * ep_ua - a_epe_epi_ua * epe_ua\n",
    "    depi_ua = a_epe_epi_ua * epe_ua - e_epi_ctl_ua * epi_ua * ctl_act_ua - d_epi_ua * epi_ua\n",
    "    didc_ua = d_idc_ua * idc_0_ua - d_idc_ua * idc_ua + p_idc_ua * idc_ua * (v_ua/(v_ua + s_v_idc_recr_ua)) - m_idc_ln_ua * idc_ua * (v_ua/(v_ua + s_v_idc_migr_ua))\n",
    "    dmdc_ua = m_idc_ln_ua * idc_ua * (v_ua/(v_ua + s_v_idc_migr_ua)) - d_mdc_ua * mdc_ua\n",
    "    dtn_ua = p_cd8_ua * tn_ua * (mdc_ua/(mdc_ua + s_mdc_cd8_prol_ua)) - a_cd8_ctl_ua * tn_ua * (mdc_ua/(mdc_ua + s_mdc_cd8_diff_ua)) - d_cd8_ua * tn_ua + d_cd8_ua * cd8_ua\n",
    "    dctl_ua = a_cd8_ctl_ua * tn_ua * (mdc_ua/(mdc_ua + s_mdc_cd8_diff_ua)) - d_ctl_ua * ctl_ua\n",
    "    dctl_act_ua = m_ctl_ua * h(p, t-t_ctl_ua)[8] - d_ctl_ua * ctl_act_ua\n",
    "    dbn_ua = p_b_ua * bn_ua * (mdc_ua/(mdc_ua + s_mdc_b_prol_ua)) - d_b_ua * bn_ua + d_b_ua * b_0_ua - a_b_ua * bn_ua * (mdc_ua/(mdc_ua + s_mdc_b_diff_ua))\n",
    "    dp_ua = a_b_ua * bn_ua * (mdc_ua/(mdc_ua + s_mdc_b_diff_ua)) - d_p_ua * p_ua\n",
    "    dig_ua = r_ig_ua * p_ua - d_ig_ua * ig_ua\n",
    "\n",
    "    dv_l = m_v_lungs * v_ua + r_v * epi_l - d_v * v_l - e_6 * e_v_igg * v_l * igg_l - e_6 * e_v_iga * v_l * iga_l - e_6 * e_v_igm * v_l * igm_l\n",
    "    dep_l = d_ep * ep_0 - d_ep * ep_l - i_v_ep * ep_l * v_l * (s_ifn_ep_inf/(s_ifn_ep_inf + igamma_l))\n",
    "    depe_l = i_v_ep * ep_l * v_l * (s_ifn_ep_inf/(s_ifn_ep_inf + igamma_l)) - a_epe_epi * epe_l\n",
    "    depi_l = a_epe_epi * epe_l - e_7 * e_epi_ctl * epi_l * ctl_act_l * (s_il6_epi_elim/(s_il6_epi_elim+i6_l)) - d_epi * epi_l\n",
    "    didc_l = d_idc * idc_0 - d_idc * idc_l + p_idc * idc_l * (v_l/(v_l + s_v_idc_recr)) - e_5 * m_idc_ln * h(p, t-t_idc)[17] * (h(p, t-t_idc)[13]/(h(p, t-t_idc)[13] + s_v_idc_migr))\n",
    "    dmdc_l = e_5 * m_idc_ln * h(p, t-t_idc)[17] * (h(p, t-t_idc)[13]/(h(p, t-t_idc)[13] + s_v_idc_migr)) - d_mdc * mdc_l\n",
    "    dhn_l = d_t * cd4_0 - d_t * hn_l + e_1 * p_cd4 * hn_l * (mdc_l/(mdc_l + s_mdc_cd4_prol)) * (s_il6_t_prol/(s_il6_t_prol + i6_l)) - a_cd4_th1 * hn_l * (i12_l/(i12_l + s_il12_cd4_diff)) - a_cd4_tfh * hn_l * (i6_l/(i6_l + s_il6_cd4_diff))\n",
    "    dtn_l = d_t * cd8_n - d_t * tn_l + e_2 * p_cd8 * tn_l * (mdc_l/(mdc_l + s_mdc_cd8_prol)) * (s_il6_t_prol/(s_il6_t_prol + i6_l)) * (i2_l/(i2_l + s_il2_t_prol)) - a_cd8_ctl * tn_l * (i2_l/(i2_l + s_il2_t_prol))\n",
    "    dctl_l = e_3 * a_cd8_ctl * tn_l * (i2_l/(i2_l + s_il2_t_prol)) - d_ctl * ctl_l\n",
    "    dth1_l = a_cd4_th1 * hn_l * (i12_l/(i12_l + s_il12_cd4_diff)) - d_th1 * th1_l\n",
    "    dtfh_l = a_cd4_tfh * hn_l * (i6_l/(i6_l + s_il6_cd4_diff)) - d_tfh * tfh_l\n",
    "    dctl_act_l = m_ctl_lungs * h(p, t-t_ctl)[21] - d_ctl * ctl_act_l\n",
    "    dbn_l = d_b * b_0 - d_b * bn_l + e_4 * p_b * bn_l * (mdc_l/(mdc_l + s_mdc_b_prol)) * (tfh_l/(tfh_l + s_tfh_b)) - a_b_p * bn_l * (tfh_l/(tfh_l + s_tfh_b))\n",
    "    dp_l = a_b_p * bn_l * (tfh_l/(tfh_l + s_tfh_b)) - d_p * p_l\n",
    "    digg_l = r_igg * p_l - d_igg * igg_l\n",
    "    diga_l = r_iga * p_l - d_iga * iga_l\n",
    "    digm_l = r_igm * p_l - d_igm * igm_l\n",
    "    dmr_l = d_mr * m_0 - d_mr * mr_l + p_mr * ma_l + a_ma_mr * ma_l - e_8 * a_mr_ma * mr_l * (igamma_l/(igamma_l + s_ifn_mr_act)) * (v_l/(v_l + s_v_mr_act))\n",
    "    dma_l = e_8 * a_mr_ma * mr_l * (igamma_l/(igamma_l + s_ifn_mr_act)) * (v_l/(v_l + s_v_mr_act)) - a_ma_mr * ma_l - d_ma * ma_l\n",
    "    digamma_l = r_ifn_th1 * th1_l * (v_l/(v_l + s_v_ifn_prod)) + r_ifn_ctl * ctl_l * (v_l/(v_l + s_v_ifn_prod)) - d_ifn * igamma_l\n",
    "    di2_l = r_il2_th1 * th1_l + r_il2_tfh * tfh_l - d_il2 * i2_l\n",
    "    di6_l = r_il6_epi * epi_l + r_il6_ma * ma_l - d_il6 * i6_l\n",
    "    di12_l = r_il12_ma * ma_l + r_il12_mdc * mdc_l - d_il12 * i12_l\n",
    "    \n",
    "    du .= [dv_ua, dep_ua, depe_ua, depi_ua, didc_ua, dmdc_ua, dtn_ua, dctl_ua, dctl_act_ua, dbn_ua, dp_ua, dig_ua, dv_l, dep_l, depe_l, depi_l, didc_l, dmdc_l, dhn_l, dtn_l, dctl_l, dth1_l, dtfh_l, dctl_act_l, dbn_l, dp_l, digg_l, diga_l, digm_l, dmr_l, dma_l, digamma_l, di2_l, di6_l, di12_l]\n",
    "    \n",
    "    nothing\n",
    "end\n",
    "\n",
    "\n",
    "p = (r_v_epi_ua = 10.0, k_v_degr = 0.5, e_v_ig_ua = 0.5, m_v_lungs = 0.1, d_ep_ua = 0.8, ep_0_ua = 5500000.0,\n",
    "    i_v_ep_ua = 1.5e-7, a_epe_epi_ua = 1.65, e_epi_ctl_ua = 0.001, d_epi_ua = 0.5, d_idc_ua = 0.13,\n",
    "    idc_0_ua = 2500000.0, p_idc_ua = 0.15, s_v_idc_recr_ua = 1.0e7, m_idc_ln_ua = 0.3, s_v_idc_migr_ua = 5000000.0,\n",
    "    d_mdc_ua = 0.5, p_cd8_ua = 15.0, s_mdc_cd8_prol_ua = 1.0e7, a_cd8_ctl_ua = 22.0, s_mdc_cd8_diff_ua = 1.0e7,\n",
    "    d_cd8_ua = 0.008, cd8_ua = 16000.0, d_ctl_ua = 0.05, m_ctl_ua = 0.015, p_b_ua = 5.5, s_mdc_b_prol_ua = 1.0e7,\n",
    "    d_b_ua = 0.008, b_0_ua = 33000.0, a_b_ua = 6.0, s_mdc_b_diff_ua = 1.0e7, d_p_ua = 0.2, r_ig_ua = 3.0e-5,\n",
    "    d_ig_ua = 0.025, t_ctl_ua = 0.5,\n",
    "        ep_0 = 5.5E8, idc_0 = 1200000.0, m_0 = 400000.0, p_mr = 0.3, i_v_ep = 1.1E-9,\n",
    "    p_idc = 0.2, r_v = 10.0, a_mr_ma = 4.0, s_v_mr_act = 1.0E9, s_v_idc_recr = 1.0E9, s_ifn_ep_inf = 200.0,\n",
    "    a_ma_mr = 0.36, a_epe_epi = 0.7, e_epi_ctl = 0.005, e_v_igg = 0.5, e_v_iga = 0.5, e_v_igm = 0.5,\n",
    "    d_v = 0.5, d_idc = 0.13, d_ep = 0.005, d_epi = 0.5, d_ma = 0.3, d_mr = 0.02,\n",
    "    m_ctl_lungs = 0.02, s_ifn_mr_act = 5.0, t_ctl = 0.5, b_0 = 60000.0, cd4_0 = 100000.0,\n",
    "    cd8_n = 33000.0, s_il2_t_prol = 20.0, r_ifn_th1 = 0.005, r_il12_ma = 8.0E-4, r_il12_mdc = 3.0E-5,\n",
    "    r_iga = 7.0E-6, r_igg = 6.0E-6, r_igm = 6.5E-6, p_b = 1.4, r_ifn_ctl = 0.01,\n",
    "    a_cd8_ctl = 4.5, a_cd4_th1 = 0.8, a_cd4_tfh = 0.4, a_b_p = 0.82, s_mdc_b_prol = 17600.0, s_v_idc_migr = 1.0E9,\n",
    "    s_mdc_cd8_prol = 5000.0, s_mdc_cd4_prol = 15000.0, s_il6_t_prol = 800.0, p_cd4 = 1.4, p_cd8 = 5.1,\n",
    "    r_il6_epi = 1.0E-5, r_il2_tfh = 3.0E-4, r_il2_th1 = 3.0E-4, r_il6_ma = 0.0035, d_iga = 0.08,\n",
    "    d_igg = 0.04, d_igm = 0.1, d_b = 0.008, d_mdc = 0.5, d_p = 0.2, d_t = 0.008, d_il6 = 1.0,\n",
    "    d_il12 = 1.4, d_th1 = 0.05, d_tfh = 0.05, d_ifn = 4.0, d_ctl = 0.05, d_il2 = 15.0,\n",
    "    m_idc_ln = 2.0, s_tfh_b = 300000.0, s_il12_cd4_diff = 5.0, s_il6_cd4_diff = 5.0, s_v_ifn_prod = 1.0E7, t_idc = 0.8,\n",
    "    e_1 = 1.0, e_2 = 1.0, e_3 = 1.0, e_4 = 1.0,\n",
    "    e_5 = 1.0, e_6 = 1.0, e_7 = 1.0, e_8 = 1.0, s_il6_epi_elim = 400.0)\n",
    "\n",
    "initial_values = (v_ua = 1000.0, ep_ua = 5500000.0, epe_ua =  0.0, epi_ua =  0.0, idc_ua =  2500000.0, mdc_ua =  0.0,\n",
    "    tn_ua =  16000.0, ctl_ua =  0.0, ctl_act_ua =  0.0, bn_ua =  33000.0, p_ua = 0.0 , ig_ua = 0.0,\n",
    "    v_l = 0.0, ep_l = 5.5e8, epe_l = 0.0, epi_l = 0.0, idc_l = 1200000.0, mdc_l = 0.0, hn_l = 100000.0, tn_l = 33000.0, ctl_l = 0.0, th1_l = 0.0,\n",
    "    tfh_l = 0.0, ctl_act_l = 0.0, bn_l = 60000.0, p_l = 0.0, igg_l = 0.0, iga_l = 0.0, igm_l = 0.0,\n",
    "    mr_l = 400000.0, ma_l = 0.0, igamma_l = 0.0, i2_l = 0.0, i6_l = 0.0, i12_l = 0.0\n",
    "    )\n",
    "\n",
    "u0 = [initial_values.v_ua, initial_values.ep_ua, initial_values.epe_ua, initial_values.epi_ua, initial_values.idc_ua, initial_values.mdc_ua,\n",
    "    initial_values.tn_ua, initial_values.ctl_ua, initial_values.ctl_act_ua, initial_values.bn_ua, initial_values.p_ua, initial_values.ig_ua,\n",
    "    initial_values.v_l, initial_values.ep_l, initial_values.epe_l, initial_values.epi_l, initial_values.idc_l, initial_values.mdc_l,\n",
    "    initial_values.hn_l, initial_values.tn_l, initial_values.ctl_l, initial_values.th1_l, initial_values.tfh_l, initial_values.ctl_act_l,\n",
    "    initial_values.bn_l, initial_values.p_l, initial_values.igg_l, initial_values.iga_l, initial_values.igm_l, initial_values.mr_l,\n",
    "    initial_values.ma_l, initial_values.igamma_l, initial_values.i2_l, initial_values.i6_l, initial_values.i12_l]\n",
    "h(p, t) = u0\n",
    "\n",
    "tspan = (0.0, 60.0)\n",
    "\n",
    "prob = DDEProblem(model!, u0, h, tspan, p)\n",
    "\n",
    "function affect!(integrator)\n",
    "    u = integrator.u\n",
    "    u[1] = 0\n",
    "    u[3] = 0\n",
    "    u[4] = 0\n",
    "    u[13] = 0\n",
    "    u[15] = 0\n",
    "    u[16] = 0\n",
    "end\n",
    "\n",
    "function condition(u, t, integrator)\n",
    "    return (u[1] < 1 || u[13] < 1) && t > 10.0\n",
    "end\n",
    "\n",
    "cb = DiscreteCallback(condition, affect!)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48af9d6a-07c1-4f3b-8847-41386b023efc",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "begin\n",
    "    sol = solve(prob, MethodOfSteps(BS3()), abstol=1.0E-20, reltol=1.0E-12, callback=cb, saveat=0.5)\n",
    "    \n",
    "    var_nam = [\n",
    "        \"t\", \"v_ua\", \"ep_ua\", \"epe_ua\", \"epi_ua\", \"idc_ua\", \"mdc_ua\", \"tn_ua\", \"ctl_ua\", \"ctl_act_ua\", \"bn_ua\", \"p_ua\", \"ig_ua\", \"v_l\", \"ep_l\", \"epe_l\", \"epi_l\", \"idc_l\", \"mdc_l\",\n",
    "        \"hn_l\", \"tn_l\", \"ctl_l\", \"th1_l\", \"tfh_l\", \"ctl_act_l\", \"bn_l\", \"p_l\", \"igg_l\", \"iga_l\", \"igm_l\", \"mr_l\", \"ma_l\",\n",
    "        \"igamma_l\", \"i2_l\", \"i6_l\", \"i12_l\"\n",
    "    ]\n",
    "    df = DataFrame(sol)\n",
    "    rename!(df, names(df) .=> var_nam)\n",
    "end"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d24ac6d1-f52b-4030-9de3-65c150d3ef0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot( \n",
    "    plot(df.t, df.v_ua, label=\"V\", title=\"Viral load (ua)\"),\n",
    "    plot(df.t, [df.ep_ua, df.epe_ua, df.epi_ua], label=[\"EP\" \"EPe\" \"EPi\"], title=\"Epithelial cells (ua)\"),\n",
    "    plot(df.t, [df.idc_ua, df.mdc_ua], label=[\"IDC\" \"MDC\"], title=\"Dendritic cells (ua)\"),\n",
    "    plot(df.t, [df.tn_ua, df.ctl_ua, df.ctl_act_ua], label=[\"Tn\" \"CTLs\" \"CTLs ua\"], title=\"CD8+ T cells (ua)\"),\n",
    "    plot(df.t, [df.bn_ua, df.p_ua], label=[\"Bn\" \"P\"], title=\"B cells (ua)\"),\n",
    "    plot(df.t, df.ig_ua, label=\"Ig\", title=\"Antibodies (ua)\"),\n",
    "    \n",
    "    plot(df.t, df.v_l, label=\"V\", title=\"Viral load\"),\n",
    "    plot(df.t, [df.ep_l, df.epe_l, df.epi_l], label=[\"EP\" \"EPe\" \"EPi\"], title=\"Epithelial cells\"),\n",
    "    plot(df.t, [df.idc_l, df.mdc_l], label=[\"IDC\" \"MDC\"], title=\"Dendritic cells\"),\n",
    "    plot(df.t, [df.tn_l, df.ctl_l, df.ctl_act_l], label=[\"Tn\" \"CTLs\" \"CTLs lungs\"], title=\"CD8+ T cells\"),\n",
    "    plot(df.t, [df.hn_l, df.th1_l, df.tfh_l], label=[\"Hn\" \"Th1\" \"Tfh\"], title=\"CD4+ T cells\"),\n",
    "    plot(df.t, [df.bn_l, df.p_l], label=[\"Bn\" \"P\"], title=\"B cells\"),\n",
    "    plot(df.t, [df.igg_l, df.iga_l, df.igm_l], label=[\"IgG\" \"IgA\" \"IgM\"], title=\"Antibodies\"),\n",
    "    plot(df.t, [df.mr_l, df.ma_l], label=[\"Mr\" \"Ma\"], title=\"Macrophages\"),\n",
    "    plot(df.t, [df.igamma_l, df.i2_l, df.i6_l, df.i12_l], label=[\"IFNg\" \"IL-2\" \"IL-6\" \"IL-12\"], title=\"Cytokines\"),\n",
    "    layout=(5,3), size=(1000,1000), legend=:topright\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "07ef9a02-69fb-414b-bc50-723bcb4950e8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Julia 1.10.3",
   "language": "julia",
   "name": "julia-1.10"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "1.10.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
